name: First work flow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: windows-latest
    steps:
      - name: first-step
        run: echo "Hello World"
      - name: good-bye
        run: echo "Good bye my friend"
